### ISSUE TITLE
hyperlink clicks vs hyperlink_clicked

### ISSUE THREAD

**Issue by heatherkoff** [edsp2016/charlieguthrie#3]
Hi Charlie,

A couple comments...

I see that you did some kind of conversion on hyperlinks outcome variable, changing from hyperlink_clicks to hyperlink_clicked. This conversion seems to happen on a number of variables. What does this mean?

Also, it would be really helpful to see your comments, output, and tables in a readable output document. I see that you made classification trees and calculated prediction accuracy in a series of logistic regression models. However, I don't see any of the output printed in the .Rmd document on GitHub. Perhaps I could download the train and test data sets and run the code myself, but I don't see these data sets posted. I'd look at it more closely if I didn't have to go through the extra steps of downloading, storing, changing working directory, and then running.

~Heather

**Comment by charlesdguthrie** [comment]
Hi Heather thanks for the comments.  I'm not sure why the output doesn't get printed to the .Rmd document.  Perhaps it needs to be run first? I'll look into getting the output in there.

**Comment by charlesdguthrie** [comment]
My best solution right now is to download notebooks/project_log.html, which does display the results.  Unfortunately github won't render the html for you.

**Comment by heatherkoff** [comment]
I think downloading that .html file only works on your computer. Not sure though.

The method for making .md files display plots and output in GitHub is:

This was working me before I switched to rendering pdfs in beamer, you could give it a try:

You just add this code at the top of the .Rmd file, instead of outputting to html_document (or whatever else):

output: 
md_document:
variant: markdown_github

Then you just click "Knit"-- the .md file on your computer won't show the output, but it will in GitHub.

**Comment by charlesdguthrie** [comment]
Great thanks!

**Comment by charlesdguthrie** [comment]
Thanks to your help all my results are now on the front page, in the README.md file.
