### ISSUE TITLE
Weekly Review

### ISSUE THREAD

**Issue by bombsandbottles** [edsp2016/charlieguthrie#4]
Hey Charlie,

So after reading your updated log, is it correct that you are now trying to come up with the best way to measure each individual cards performance, and also how each preceding card effects the subsequent cards performance?

Unless I missed it, I couldn't find the results from your previous tests.

**Comment by charlesdguthrie** [comment]
Yes that's right.  I've uploaded some results to the README on the front page, but still in the process of running models for the other cards.
